# Custom config for RuboCop static code analysis
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 50

Style/SignalException:
  EnforcedStyle: only_raise

Style/RaiseArgs:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/HashSyntax:
  UseHashRocketsWithSymbolValues: true

Style/AlignHash:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/IndentHash:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/GlobalVars:
  Description: 'Do not introduce global variables.'
  StyleGuide: '#instance-vars'
  Reference: 'http://www.zenspider.com/Languages/Ruby/QuickRef.html'
  Enabled: false

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Enabled: false


